# plugins

# TPM

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'tmux-plugins/tmux-yank'

#

set -g mouse on

set -g display-panes-time 10000

bind - split-window -v -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"

bind c new-window -c "#{pane_current_path}"

#

set -g status-position bottom

set -g status-left ' #{=/20/…:session_name} '
set -g status-left-length 23 # status-leftに依存 (' ' + 20文字 + '…' + ' ')
set -g status-left-style 'bg=colour255 fg=colour202 bold'

set -g status-right ' '
set -g status-right-length 1

set -g status-style 'bg=colour232 fg=colour255'

set -g window-status-format ' #{window_index} #{window_name}#{?window_zoomed_flag,  ,} '
set -g window-status-current-format ' #{window_index} #{window_name}#{?window_zoomed_flag,  ,} '
set -g window-status-current-style 'bg=colour202 fg=colour255 bold'

set -g pane-border-style 'bg=colour232 fg=colour232'
set -g pane-active-border-style 'bg=colour202 fg=colour202'

# TPM

run '~/.tmux/plugins/tpm/tpm'

