# 基本 {{{
set-option -ga terminal-overrides ",xterm-256color:Tc"

set -g display-panes-time 10000

set -g mouse on

set -sg escape-time 10
# 基本 }}}

# マップ {{{
set -g prefix C-\\
unbind C-b

bind C-\\ display-panes

set -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection

bind r source-file ~/.tmux.conf \; display "Reloaded!"

bind - split-window -v -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"

bind k select-pane -U
bind j select-pane -D
bind h select-pane -L
bind l select-pane -R

bind K swap-pane -U
bind J swap-pane -D
bind H swap-pane -s '{left-of}'
bind L swap-pane -s '{right-of}'

bind -n S-Left select-window -p
bind -n S-Right select-window -n

bind P swap-window -t:-\; select-window -t:-
bind N swap-window -t:+\; select-window -t:+

bind -n S-Up switch-client -p
bind -n S-Down switch-client -n
# マップ }}}

# プラグイン {{{
# tpm {{{
set -g @plugin 'seebi/tmux-colors-solarized'
set -g @colors-solarized '256'

set -g @plugin 'tmux-plugins/tmux-yank'

run '~/.tmux/plugins/tpm/tpm'
# tpm }}}
# プラグイン }}}

# vim: fdm=marker
