# plugins

# TPM

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'tmux-plugins/tmux-yank'

#

# True Color Support
set -sa terminal-overrides ",*-256color:Tc"

set -g mouse on

set -g display-panes-time 10000

# Binds

# Pane

bind h split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"

bind -n C-M-Left select-pane -L
bind -n C-M-Right select-pane -R
bind -n C-M-Up select-pane -U
bind -n C-M-Down select-pane -D

bind -n C-M-S-Left resize-pane -L 5
bind -n C-M-S-Down resize-pane -D 5
bind -n C-M-S-Up resize-pane -U 5
bind -n C-M-S-Right resize-pane -R 5

# Window

bind c new-window -c "#{pane_current_path}"

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

bind -n M-Left select-window -t -1
bind -n M-Right select-window -t +1
bind -n M-S-Left swap-window -t -1 \; select-window -t -1
bind -n M-S-Right swap-window -t +1 \; select-window -t +1

# Session

bind C new-session -c "#{pane_current_path}"

#

set -g status-position top

set -g status-left ' #{=/20/…:session_name} '
set -g status-left-length 23 # status-leftに依存 (' ' + 20文字 + '…' + ' ')
set -g status-left-style 'bg=colour255 fg=colour202 bold'

set -g status-right ' '
set -g status-right-length 1

set -g status-style 'bg=colour232 fg=colour255'

set -g window-status-format ' #{window_index} #{window_name}#{?window_zoomed_flag,  ,} '
set -g window-status-current-format ' #{window_index} #{window_name}#{?window_zoomed_flag,  ,} '
set -g window-status-current-style 'bg=colour202 fg=colour255 bold'

set -g pane-border-style 'fg=colour232'
set -g pane-active-border-style 'fg=colour202'

# TPM

run '~/.tmux/plugins/tpm/tpm'

# vim: set ft=tmux:
